//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `CumbiaChat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CumbiaChat;

public class Message implements java.lang.Cloneable,
                                java.io.Serializable
{
    public String sender;

    public String content;

    public String type;

    public String date;

    public Message()
    {
        this.sender = "";
        this.content = "";
        this.type = "";
        this.date = "";
    }

    public Message(String sender, String content, String type, String date)
    {
        this.sender = sender;
        this.content = content;
        this.type = type;
        this.date = date;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Message r = null;
        if(rhs instanceof Message)
        {
            r = (Message)rhs;
        }

        if(r != null)
        {
            if(this.sender != r.sender)
            {
                if(this.sender == null || r.sender == null || !this.sender.equals(r.sender))
                {
                    return false;
                }
            }
            if(this.content != r.content)
            {
                if(this.content == null || r.content == null || !this.content.equals(r.content))
                {
                    return false;
                }
            }
            if(this.type != r.type)
            {
                if(this.type == null || r.type == null || !this.type.equals(r.type))
                {
                    return false;
                }
            }
            if(this.date != r.date)
            {
                if(this.date == null || r.date == null || !this.date.equals(r.date))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::CumbiaChat::Message");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sender);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, content);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, type);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, date);
        return h_;
    }

    public Message clone()
    {
        Message c = null;
        try
        {
            c = (Message)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.sender);
        ostr.writeString(this.content);
        ostr.writeString(this.type);
        ostr.writeString(this.date);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.sender = istr.readString();
        this.content = istr.readString();
        this.type = istr.readString();
        this.date = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Message v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Message ice_read(com.zeroc.Ice.InputStream istr)
    {
        Message v = new Message();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Message> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Message v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Message> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Message.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Message _nullMarshalValue = new Message();

    /** @hidden */
    public static final long serialVersionUID = -266545151L;
}
