//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `audio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CumbiaChat;

/** @hidden */
public class _AudioCallbackPrxI extends com.zeroc.Ice._ObjectPrxI implements AudioCallbackPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
