//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `audio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CumbiaChat;

public interface AudioServerPrx extends com.zeroc.Ice.ObjectPrx
{
    /**
     * Unirse a una sala de voz
     * @param roomName Nombre del grupo/sala
     * @param username Nombre del usuario
     * @return true si se unió exitosamente
     **/
    default boolean joinRoom(String roomName, String username)
    {
        return joinRoom(roomName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Unirse a una sala de voz
     * @param roomName Nombre del grupo/sala
     * @param username Nombre del usuario
     * @param context The Context map to send with the invocation.
     * @return true si se unió exitosamente
     **/
    default boolean joinRoom(String roomName, String username, java.util.Map<String, String> context)
    {
        return _iceI_joinRoomAsync(roomName, username, context, true).waitForResponse();
    }

    /**
     * Unirse a una sala de voz
     * @param roomName Nombre del grupo/sala
     * @param username Nombre del usuario
     * @return true si se unió exitosamente
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Boolean> joinRoomAsync(String roomName, String username)
    {
        return _iceI_joinRoomAsync(roomName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Unirse a una sala de voz
     * @param roomName Nombre del grupo/sala
     * @param username Nombre del usuario
     * @param context The Context map to send with the invocation.
     * @return true si se unió exitosamente
     **/
    default java.util.concurrent.CompletableFuture<java.lang.Boolean> joinRoomAsync(String roomName, String username, java.util.Map<String, String> context)
    {
        return _iceI_joinRoomAsync(roomName, username, context, false);
    }

    /**
     * @hidden
     * @param iceP_roomName -
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_joinRoomAsync(String iceP_roomName, String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "joinRoom", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_roomName);
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /**
     * Salir de la sala de voz actual
     **/
    default void leaveCall()
    {
        leaveCall(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Salir de la sala de voz actual
     * @param context The Context map to send with the invocation.
     **/
    default void leaveCall(java.util.Map<String, String> context)
    {
        _iceI_leaveCallAsync(context, true).waitForResponse();
    }

    /**
     * Salir de la sala de voz actual
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> leaveCallAsync()
    {
        return _iceI_leaveCallAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Salir de la sala de voz actual
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> leaveCallAsync(java.util.Map<String, String> context)
    {
        return _iceI_leaveCallAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_leaveCallAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "leaveCall", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    /**
     * Enviar paquete de audio al servidor
     * @param data Datos de audio en formato PCM
     **/
    default void sendAudioPacket(byte[] data)
    {
        sendAudioPacket(data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Enviar paquete de audio al servidor
     * @param data Datos de audio en formato PCM
     * @param context The Context map to send with the invocation.
     **/
    default void sendAudioPacket(byte[] data, java.util.Map<String, String> context)
    {
        _iceI_sendAudioPacketAsync(data, context, true).waitForResponse();
    }

    /**
     * Enviar paquete de audio al servidor
     * @param data Datos de audio en formato PCM
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> sendAudioPacketAsync(byte[] data)
    {
        return _iceI_sendAudioPacketAsync(data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Enviar paquete de audio al servidor
     * @param data Datos de audio en formato PCM
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> sendAudioPacketAsync(byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendAudioPacketAsync(data, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendAudioPacketAsync(byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendAudioPacket", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    /**
     * Registrar callback para recibir audio
     * @param callback Proxy del callback del cliente
     **/
    default void registerCallback(AudioCallbackPrx callback)
    {
        registerCallback(callback, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Registrar callback para recibir audio
     * @param callback Proxy del callback del cliente
     * @param context The Context map to send with the invocation.
     **/
    default void registerCallback(AudioCallbackPrx callback, java.util.Map<String, String> context)
    {
        _iceI_registerCallbackAsync(callback, context, true).waitForResponse();
    }

    /**
     * Registrar callback para recibir audio
     * @param callback Proxy del callback del cliente
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> registerCallbackAsync(AudioCallbackPrx callback)
    {
        return _iceI_registerCallbackAsync(callback, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Registrar callback para recibir audio
     * @param callback Proxy del callback del cliente
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> registerCallbackAsync(AudioCallbackPrx callback, java.util.Map<String, String> context)
    {
        return _iceI_registerCallbackAsync(callback, context, false);
    }

    /**
     * @hidden
     * @param iceP_callback -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerCallbackAsync(AudioCallbackPrx iceP_callback, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerCallback", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_callback);
                 }, null);
        return f;
    }

    /**
     * Obtener lista de usuarios en la sala
     * @param roomName Nombre de la sala
     * @return Lista de nombres de usuario
     **/
    default String[] getUsersInRoom(String roomName)
    {
        return getUsersInRoom(roomName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Obtener lista de usuarios en la sala
     * @param roomName Nombre de la sala
     * @param context The Context map to send with the invocation.
     * @return Lista de nombres de usuario
     **/
    default String[] getUsersInRoom(String roomName, java.util.Map<String, String> context)
    {
        return _iceI_getUsersInRoomAsync(roomName, context, true).waitForResponse();
    }

    /**
     * Obtener lista de usuarios en la sala
     * @param roomName Nombre de la sala
     * @return Lista de nombres de usuario
     **/
    default java.util.concurrent.CompletableFuture<String[]> getUsersInRoomAsync(String roomName)
    {
        return _iceI_getUsersInRoomAsync(roomName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Obtener lista de usuarios en la sala
     * @param roomName Nombre de la sala
     * @param context The Context map to send with the invocation.
     * @return Lista de nombres de usuario
     **/
    default java.util.concurrent.CompletableFuture<String[]> getUsersInRoomAsync(String roomName, java.util.Map<String, String> context)
    {
        return _iceI_getUsersInRoomAsync(roomName, context, false);
    }

    /**
     * @hidden
     * @param iceP_roomName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getUsersInRoomAsync(String iceP_roomName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getUsersInRoom", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_roomName);
                 }, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    /**
     * Ping para verificar conexión
     **/
    default void ping()
    {
        ping(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    /**
     * Ping para verificar conexión
     * @param context The Context map to send with the invocation.
     **/
    default void ping(java.util.Map<String, String> context)
    {
        _iceI_pingAsync(context, true).waitForResponse();
    }

    /**
     * Ping para verificar conexión
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> pingAsync()
    {
        return _iceI_pingAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    /**
     * Ping para verificar conexión
     * @param context The Context map to send with the invocation.
     * @return A future that will be completed when the invocation completes.
     **/
    default java.util.concurrent.CompletableFuture<Void> pingAsync(java.util.Map<String, String> context)
    {
        return _iceI_pingAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_pingAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ping", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), AudioServerPrx.class, _AudioServerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), AudioServerPrx.class, _AudioServerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), AudioServerPrx.class, _AudioServerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AudioServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), AudioServerPrx.class, _AudioServerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static AudioServerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, AudioServerPrx.class, _AudioServerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static AudioServerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, AudioServerPrx.class, _AudioServerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default AudioServerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (AudioServerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default AudioServerPrx ice_adapterId(String newAdapterId)
    {
        return (AudioServerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default AudioServerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (AudioServerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default AudioServerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (AudioServerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default AudioServerPrx ice_invocationTimeout(int newTimeout)
    {
        return (AudioServerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default AudioServerPrx ice_connectionCached(boolean newCache)
    {
        return (AudioServerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default AudioServerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (AudioServerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AudioServerPrx ice_secure(boolean b)
    {
        return (AudioServerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default AudioServerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (AudioServerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AudioServerPrx ice_preferSecure(boolean b)
    {
        return (AudioServerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default AudioServerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (AudioServerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default AudioServerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (AudioServerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default AudioServerPrx ice_collocationOptimized(boolean b)
    {
        return (AudioServerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default AudioServerPrx ice_twoway()
    {
        return (AudioServerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default AudioServerPrx ice_oneway()
    {
        return (AudioServerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default AudioServerPrx ice_batchOneway()
    {
        return (AudioServerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default AudioServerPrx ice_datagram()
    {
        return (AudioServerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default AudioServerPrx ice_batchDatagram()
    {
        return (AudioServerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default AudioServerPrx ice_compress(boolean co)
    {
        return (AudioServerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default AudioServerPrx ice_timeout(int t)
    {
        return (AudioServerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default AudioServerPrx ice_connectionId(String connectionId)
    {
        return (AudioServerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default AudioServerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (AudioServerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::CumbiaChat::AudioServer";
    }
}
