//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `audio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CumbiaChat;

public interface AudioServer extends com.zeroc.Ice.Object
{
    /**
     * Unirse a una sala de voz
     * @param roomName Nombre del grupo/sala
     * @param username Nombre del usuario
     * @param current The Current object for the invocation.
     * @return true si se unió exitosamente
     **/
    boolean joinRoom(String roomName, String username, com.zeroc.Ice.Current current);

    /**
     * Salir de la sala de voz actual
     * @param current The Current object for the invocation.
     **/
    void leaveCall(com.zeroc.Ice.Current current);

    /**
     * Enviar paquete de audio al servidor
     * @param data Datos de audio en formato PCM
     * @param current The Current object for the invocation.
     **/
    void sendAudioPacket(byte[] data, com.zeroc.Ice.Current current);

    /**
     * Registrar callback para recibir audio
     * @param callback Proxy del callback del cliente
     * @param current The Current object for the invocation.
     **/
    void registerCallback(AudioCallbackPrx callback, com.zeroc.Ice.Current current);

    /**
     * Obtener lista de usuarios en la sala
     * @param roomName Nombre de la sala
     * @param current The Current object for the invocation.
     * @return Lista de nombres de usuario
     **/
    String[] getUsersInRoom(String roomName, com.zeroc.Ice.Current current);

    /**
     * Ping para verificar conexión
     * @param current The Current object for the invocation.
     **/
    void ping(com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::CumbiaChat::AudioServer",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::CumbiaChat::AudioServer";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_joinRoom(AudioServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_roomName;
        String iceP_username;
        iceP_roomName = istr.readString();
        iceP_username = istr.readString();
        inS.endReadParams();
        boolean ret = obj.joinRoom(iceP_roomName, iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_leaveCall(AudioServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        obj.leaveCall(current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendAudioPacket(AudioServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        byte[] iceP_data;
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.sendAudioPacket(iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_registerCallback(AudioServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        AudioCallbackPrx iceP_callback;
        iceP_callback = AudioCallbackPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.registerCallback(iceP_callback, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getUsersInRoom(AudioServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_roomName;
        iceP_roomName = istr.readString();
        inS.endReadParams();
        String[] ret = obj.getUsersInRoom(iceP_roomName, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_ping(AudioServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        obj.ping(current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "getUsersInRoom",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "joinRoom",
        "leaveCall",
        "ping",
        "registerCallback",
        "sendAudioPacket"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_getUsersInRoom(this, in, current);
            }
            case 1:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 5:
            {
                return _iceD_joinRoom(this, in, current);
            }
            case 6:
            {
                return _iceD_leaveCall(this, in, current);
            }
            case 7:
            {
                return _iceD_ping(this, in, current);
            }
            case 8:
            {
                return _iceD_registerCallback(this, in, current);
            }
            case 9:
            {
                return _iceD_sendAudioPacket(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
