//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `CumbiaChat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let CumbiaChat = _ModuleRegistry.module("CumbiaChat");

    Slice.defineSequence(CumbiaChat, "AudioDataHelper", "Ice.ByteHelper", true);

    Slice.defineSequence(CumbiaChat, "StringListHelper", "Ice.StringHelper", false);

    CumbiaChat.Message = class
    {
        constructor(sender = "", content = "", type = "", date = "")
        {
            this.sender = sender;
            this.content = content;
            this.type = type;
            this.date = date;
        }

        _write(ostr)
        {
            ostr.writeString(this.sender);
            ostr.writeString(this.content);
            ostr.writeString(this.type);
            ostr.writeString(this.date);
        }

        _read(istr)
        {
            this.sender = istr.readString();
            this.content = istr.readString();
            this.type = istr.readString();
            this.date = istr.readString();
        }

        static get minWireSize()
        {
            return  4;
        }
    };

    Slice.defineStruct(CumbiaChat.Message, true, true);

    Slice.defineSequence(CumbiaChat, "MessageListHelper", "CumbiaChat.Message", false);

    const iceC_CumbiaChat_ChatCallback_ids = [
        "::CumbiaChat::ChatCallback",
        "::Ice::Object"
    ];

    CumbiaChat.ChatCallback = class extends Ice.Object
    {
    };

    CumbiaChat.ChatCallbackPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(CumbiaChat.ChatCallback, CumbiaChat.ChatCallbackPrx, iceC_CumbiaChat_ChatCallback_ids, 0,
    {
        "receiveMessage": [, , , , , [[CumbiaChat.Message], [7]], , , , ]
    });

    const iceC_CumbiaChat_ChatService_ids = [
        "::CumbiaChat::ChatService",
        "::Ice::Object"
    ];

    CumbiaChat.ChatService = class extends Ice.Object
    {
    };

    CumbiaChat.ChatServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(CumbiaChat.ChatService, CumbiaChat.ChatServicePrx, iceC_CumbiaChat_ChatService_ids, 0,
    {
        "login": [, , , , [1], [[7], [7], ["CumbiaChat.ChatCallbackPrx"]], , , , ],
        "createGroup": [, , , , , [[7], [7]], , , , ],
        "getGroups": [, , , , ["CumbiaChat.StringListHelper"], , , , , ],
        "joinGroup": [, , , , [1], [[7], [7]], , , , ],
        "sendMessage": [, , , , , [[7], [7], [7], [7]], , , , ],
        "sendAudio": [, , , , , [["CumbiaChat.AudioDataHelper"], [7], [7], [7]], , , , ],
        "getHistory": [, , , , ["CumbiaChat.MessageListHelper"], [[7]], , , , ]
    });
    exports.CumbiaChat = CumbiaChat;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
